version: 2
jobs:
  test-py27:
    docker:
      - image: circleci/python:2.7
    environment:
      - DJANGO_VERSIONS: "18;19;110;111"
    steps:
      - checkout
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Install tox
          command: |
            source venv/bin/activate
            pip install tox
      - run:
          name: Run tests with tox
          command: |
            source venv/bin/activate
            tox
  test-py36:
    docker:
      - image: circleci/python:3.6
    environment:
      - DJANGO_VERSIONS: "111;20"
    steps:
      - checkout
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Install tox
          command: |
            source venv/bin/activate
            pip install tox
      - run:
          name: Run tests with tox
          command: |
            source venv/bin/activate
            tox
workflows:
  version: 2
  test-py27-and-test-py3:
    jobs:
      - test-py27
      - test-py3:
          
