version: 2
jobs:
  test-py27: &test-template
    docker:
      - image: circleci/python:2.7
    environment:
      - DJANGO_VERSIONS: "18;19;110;111"
    steps:
      - checkout
      - run:
          name: Setup a virtualenv
          command: virtualenv venv
      - run:
          name: Install tox
          command: |
            source venv/bin/activate
            pip install tox
      - run:
          name: Run tests with tox
          command: |
            source venv/bin/activate
            tox
  test-py36:
    <<: *test-template
    docker:
      - image: circleci/python:3.6
    environment:
      - DJANGO_VERSIONS: "111;20"
workflows:
  version: 2
  py27-and-py3:
    jobs:
      - py27
      - py3:
          requires:
            - py27
